### ISSUE TITLE
Rounding errors in values in KiCad netlist

### ISSUE THREAD

**Issue by JasperZP** [faebryk/faebryk#157]
### Current Behaviour

For a capacitor with value 100uF, it prints a value in the KiCad netlist output of:
`node (ref power_section.power_selector_priority.switches[1].capacitor[Capacitor:99.99999999999999µF`

### Expected Behaviour

Expected output would be 
`node (ref power_section.power_selector_priority.switches[1].capacitor[Capacitor:100µF`

### Possible Solution

Rounding the value to a few digits.

### Version

main@f60313

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IoannisPZP** [comment]
Note: Fix problem here: https://github.com/faebryk/faebryk/blob/main/src/faebryk/library/util.py#L38
