### ISSUE TITLE
KeyError in nx.draw_networkx_labels() function

### ISSUE THREAD

**Issue by ruben-iteng** [faebryk/faebryk#36]
### Current Behaviour

A KeyError occurred at line 974 in \networkx\drawing\nx_pylab.py when running samples/vindriktning.py in [my fork](https://github.com/ruben-iteng/faebryk/tree/feature/vindriktning)

### Expected Behaviour

The program exited without errors and a graph image.

### Version

0.0.1

### Relevant log output

```shell
File "C:\Users\xxxx\AppData\Roaming\Python\Python310\site-packages\networkx\drawing\nx_pylab.py", line 974, in draw_networkx_labels
    (x, y) = pos[n]
KeyError: <class 'faebryk.exporters.netlist.netlist.vertex'>({'node': 'COMP[Component:virt]@79B33342', 'pin': 1})
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IoannisP-ITENG** [comment]
Fixed in #59
