### ISSUE TITLE
Split library classes into different files

### ISSUE THREAD

**Issue by ruben-iteng** [faebryk/faebryk#41]
### Contact Details
No response

### Current Behaviour
The library is monolithic.

### Expected Behaviour
The library should be separated for easier use, maintenance, and development.

### Possible Solution
- faebryk
  - core
    - traits
      - interface
      - component
      - footprint
      - parameters
      - link
    - 1st order classes
    - FaebrykLibObjects
    - parameters
  - meta / helpers (to core?)
  - interfaces
  - footprints
  - components (general e.g. "resistor")
  - parts (specific part nr e.g. STM32F072C8T)
  - packages (3D CAD)
- external libs

### Version
No response

### Relevant log output
No response

### Code of Conduct
- [x] I agree to follow this project's Code of Conduct

**Comment by IoannisP-ITENG** [comment]
in branch feature/lib_redesign_2 done
