### ISSUE TITLE
Add github notifications to Discord

### ISSUE THREAD

**Issue by ruben-iteng** [faebryk/faebryk#44]
### Contact Details
No response

### Feature Request
Add github notifications to Discord

### Code of Conduct
- [x] I agree to follow this project's Code of Conduct

**Comment by IoannisP-ITENG** [comment]
i found this: https://dev.to/inezabonte/how-to-get-github-notifications-on-your-discord-server-2j9o

**Comment by ruben-iteng** [comment]
Should be working now

**Comment by IoannisP-ITENG** [comment]
Test

**Comment by IoannisP-ITENG** [comment]
Works 👌
