### ISSUE TITLE
Create branch protection rules

### ISSUE THREAD

**Issue by ruben-iteng** [faebryk/faebryk#57]
### Feature Request

You can create a branch protection rule to enforce certain workflows for one or more branches, such as requiring an approving review or passing status checks for all pull requests merged into the protected branch.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IoannisP-ITENG** [comment]
Done
