### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by IoannisP-ITENG** [faebryk/faebryk#61]
### Feature Request

Currently no checks/help.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IoannisP-ITENG** [comment]
https://github.com/PyCQA/isort
(has black profile)

**Comment by IoannisP-ITENG** [comment]
https://github.com/PyCQA/pylint

**Comment by IoannisP-ITENG** [comment]
Not 100% sure how to integrate.
Do we really want to force it via pre-commit-hook?

**Comment by ruben-iteng** [comment]
[Ruff](https://github.com/charliermarsh/ruff) is currently the best solution.
This issue should be resolved after development of version 3.0.0 but before it's release.
